[package]
name = "simulador_de_fluxo"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
rayon = "1.11.0"

[dependencies.colorgrad]
version = "0.8.0"
features = [
    "std",
    "ggr",
    "lab",
    "named-colors",
    "preset",
]
